<?php

/** The harness's composer.json and phpunit.xml, rewritten only when they change. */
$core = '/canva/core';
$out = '/harness';
$composer = [
    'name' => 'glitchr/canva-harness',
    'description' => 'glitchr/canva with its console: generated by docker/harness/setup.php, do not edit.',
    'type' => 'project',
    'license' => 'LGPL-3.0-or-later',
    'repositories' => [['type' => 'path', 'url' => $core, 'options' => ['symlink' => true, 'versions' => ['glitchr/canva' => '1.x-dev']]]],
    'require' => ['php' => '>=8.2', 'glitchr/canva' => '1.x-dev', 'symfony/console' => '^7.0|^8.0', 'symfony/http-client' => '^7.0|^8.0', 'symfony/var-dumper' => '^7.0|^8.0'],
    'require-dev' => ['phpunit/phpunit' => '^11.0', 'symfony/config' => '^7.0|^8.0', 'symfony/dependency-injection' => '^7.0|^8.0', 'symfony/http-kernel' => '^7.0|^8.0'],
    'autoload' => ['psr-4' => ['Canva\\Harness\\' => "$core/docker/harness/src/"]],
    'autoload-dev' => ['psr-4' => ['Canva\\Tests\\' => "$core/Tests/"]],
    'minimum-stability' => 'dev',
    'prefer-stable' => true,
    'config' => ['sort-packages' => true],
];
$phpunit = "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<phpunit bootstrap=\"vendor/autoload.php\" colors=\"true\"><testsuites><testsuite name=\"core\"><directory>$core/Tests</directory></testsuite></testsuites></phpunit>\n";
foreach (["$out/composer.json" => json_encode($composer, \JSON_PRETTY_PRINT | \JSON_UNESCAPED_SLASHES)."\n", "$out/phpunit.xml" => $phpunit] as $file => $content) {
    if (!is_file($file) || file_get_contents($file) !== $content) {
        file_put_contents($file, $content);
    }
}
